In [1]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "nhtsa_traffic_fatalities" dataset
dataset_ref = client.dataset("nhtsa_traffic_fatalities", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

# Construct a reference to the "accident_2015" table
table_ref = dataset_ref.table("accident_2015")

# API request - fetch the table
table = client.get_table(table_ref)

# Preview the first five lines of the "accident_2015" table
client.list_rows(table, max_results=5).to_dataframe()

Using Kaggle's public dataset BigQuery integration.

   state_number            ...                   timestamp_of_crash
0            19            ...            2015-09-11 20:20:00+00:00
1            19            ...            2015-11-01 00:30:00+00:00
2            19            ...            2015-05-04 16:18:00+00:00
3            19            ...            2015-11-17 12:26:00+00:00
4            19            ...            2015-10-31 04:49:00+00:00

[5 rows x 70 columns]

In [2]:
# Query to find out the number of accidents for each day of the week
query = """
        SELECT COUNT(consecutive_number) AS num_accidents, 
               EXTRACT(DAYOFWEEK FROM timestamp_of_crash) AS day_of_week
        FROM `bigquery-public-data.nhtsa_traffic_fatalities.accident_2015`
        GROUP BY day_of_week
        ORDER BY num_accidents DESC
        """

# Set up the query (cancel the query if it would use too much of 
# your quota, with the limit set to 1 GB)
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**9)
query_job = client.query(query, job_config=safe_config)

# API request - run the query, and convert the results to a pandas DataFrame
accidents_by_day = query_job.to_dataframe()

# Print the DataFrame
accidents_by_day

   num_accidents  day_of_week
0           5659            7
1           5298            1
2           4916            6
3           4460            5
4           4182            4
5           4038            2
6           3985            3

In [3]:
# Query to find out the number of accidents for each day of the week
query = """
        SELECT COUNT(consecutive_number) AS num_accidents, 
               EXTRACT(DAYOFWEEK FROM timestamp_of_crash) AS day_of_week,
               EXTRACT(QUARTER FROM timestamp_of_crash) AS quarter
        FROM `bigquery-public-data.nhtsa_traffic_fatalities.accident_2015`
        GROUP BY day_of_week, quarter
        ORDER BY quarter, num_accidents DESC
        """

# Set up the query (cancel the query if it would use too much of 
# your quota, with the limit set to 1 GB)
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**9)
query_job = client.query(query, job_config=safe_config)

# API request - run the query, and convert the results to a pandas DataFrame
accidents_by_day = query_job.to_dataframe()

# Print the DataFrame
accidents_by_day

    num_accidents  day_of_week  quarter
0            1153            7        1
1            1071            6        1
2            1065            1        1
3             911            3        1
4             878            2        1
5             876            5        1
6             801            4        1
7            1507            7        2
8            1411            1        2
9            1179            6        2
10           1071            5        2
11           1037            4        2
12           1014            2        2
13            879            3        2
14           1605            7        3
15           1526            1        3
16           1372            6        3
17           1182            4        3
18           1177            5        3
19           1075            3        3
20           1037            2        3
21           1394            7        4
22           1336            5        4
23           1296            1        4
24           1294            6        4
25           1162            4        4
26           1120            3        4
27           1109            2        4